// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  app.config@1.0.0
// spec-hash: sha256:5aaf7ac1d1d4ffc3ae6a277691a6562fe3db38f309b0a1dcf1fe89b950e0ec54
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:5d632823d06844a09412d0b74c4b682fd1ed9ac49ed8fd6688451caae1afbb1b
// ─────────────────────────────────────────────────────────────────────────
import type * as T from '../types.js';

/**
 * Straight from the contract's first example.
 *
 * Edit the example in SparkX, not this file — the same example is also the
 * backend's contract-test fixture, and the two must not drift apart.
 */
export const appConfigMock: T.AppConfigOutput = {
  "appName": "appName-1",
  "apiBaseUrl": "apiBaseUrl-2",
  "features": [
    "features-a",
    "features-b"
  ]
};
