// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  map.viewport@1.0.0
// spec-hash: sha256:33ac56be56c8f3f39a6968383715d7b7a24a98721dad165e51c0bf29c6ad3860
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:68807e32b9212e99da2e69eabffa48449dd3564968d08d2c35770ef694b8ca21
// ─────────────────────────────────────────────────────────────────────────
import type * as T from '../types.js';

/**
 * Straight from the contract's first example.
 *
 * Edit the example in SparkX, not this file — the same example is also the
 * backend's contract-test fixture, and the two must not drift apart.
 */
export const mapViewportMock: T.MapViewportOutput = {
  "bbox": [
    1,
    2,
    3,
    4
  ],
  "zoom": 12.92,
  "centerLat": 12.93,
  "centerLng": 12.94
};
