// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  map.config@1.0.0
// spec-hash: sha256:1e9307a37a257a642479feb77c66f42e762df381247040bc31255214cf5af39f
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:8a92499967025cdc34b2545be453d2cd8d7d0db17fb1af6c630e36e5f02a90d6
// ─────────────────────────────────────────────────────────────────────────
import type * as T from '../types.js';

/**
 * Straight from the contract's first example.
 *
 * Edit the example in SparkX, not this file — the same example is also the
 * backend's contract-test fixture, and the two must not drift apart.
 */
export const mapConfigMock: T.MapConfigOutput = {
  "tileUrl": "tileUrl-1",
  "defaultCenterLat": 12.92,
  "defaultCenterLng": 12.93,
  "defaultZoom": 12.94,
  "maxZoom": 12.95
};
