// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  markers.detail@1.0.0
// spec-hash: sha256:1c1d5d62cf22b3a650e946eda57d4c7ac000e08a101035b5d2f9e48cadac8a6e
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:a983d5bad151fe89caa7391c1b861b79a3a6f832c2afc3041e778dcb64c17031
// ─────────────────────────────────────────────────────────────────────────
import type * as T from '../types.js';

/**
 * Straight from the contract's first example.
 *
 * Edit the example in SparkX, not this file — the same example is also the
 * backend's contract-test fixture, and the two must not drift apart.
 */
export const markersDetailMock: T.MarkersDetailOutput = {
  "id": "id_101",
  "label": "label-2",
  "kind": "kind-3",
  "speedKph": 12.94,
  "lastSeenAt": "2026-01-01T09:05:00.000Z",
  "history": [
    {}
  ]
};
