// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  markers.stream@1.0.0
// spec-hash: sha256:9f7c6d8099a6e19e48448dd10672c0b631d0ae81c57ce2eb4ffbec602b5763f6
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:e60249a7b2bcdd24a6ade38190d0139d5b737be116f7eb58b5eae60c7548d709
// ─────────────────────────────────────────────────────────────────────────
import type * as T from '../types.js';

/**
 * Straight from the contract's first example.
 *
 * Edit the example in SparkX, not this file — the same example is also the
 * backend's contract-test fixture, and the two must not drift apart.
 */
export const markersStreamMock: T.MarkersStreamOutput = {
  "id": "id_101",
  "lat": 12.92,
  "lng": 12.93,
  "headingDeg": 12.94,
  "at": "2026-01-01T09:05:00.000Z"
};
