// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  markers.list@1.0.0
// spec-hash: sha256:cee8e41453f94899f75fd9127f87c5dce6cc95a4181d446b7ee717f365c37434
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:b93ed25da055a67aeeba19f25115b6b2912caba2f00d70fabde35f04d7554ac7
// ─────────────────────────────────────────────────────────────────────────
import type * as T from '../types.js';

/**
 * Straight from the contract's first example.
 *
 * Edit the example in SparkX, not this file — the same example is also the
 * backend's contract-test fixture, and the two must not drift apart.
 */
export const markersListMock: T.MarkersListOutput = [
  {
    "id": "id_101",
    "lat": 12.92,
    "lng": 12.93,
    "label": "label-4",
    "kind": "kind-5",
    "updatedAt": "2026-01-01T09:01:00.000Z"
  }
];
