// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  app.config@1.0.0
// spec-hash: sha256:5aaf7ac1d1d4ffc3ae6a277691a6562fe3db38f309b0a1dcf1fe89b950e0ec54
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:47d9070bc4656f43ff20c8cb68f4de171f5ea55f8785c6b44d0d27e4edad938d
// ─────────────────────────────────────────────────────────────────────────
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { notAppConfig } from '../routes/app-config.js';

/**
 * The contract test.
 *
 * It is generated from the contract's example — the same example the frontend's
 * mock is built from. That is the point: when this passes, the two sides agree.
 *
 * Replace `notAppConfig` with your real handler as soon as you have one. Until
 * then this test fails, which is exactly what a to-do looks like in code.
 */
const EXAMPLE_INPUT = {} as any;

test('app.config matches its contract example', async () => {
  const result = await notAppConfig(EXAMPLE_INPUT);
  assert.equal(typeof result, 'object', 'output should be an object');
  const first = result as any;
  assert.ok("appName" in first, 'missing required output field: appName');
  assert.ok("apiBaseUrl" in first, 'missing required output field: apiBaseUrl');
});
