// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  map.config@1.0.0
// spec-hash: sha256:1e9307a37a257a642479feb77c66f42e762df381247040bc31255214cf5af39f
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:492a65e6fe45317a6c750feec10e0889849b029536cfb985dd0e7ed45854a90a
// ─────────────────────────────────────────────────────────────────────────
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { notMapConfig } from '../routes/map-config.js';

/**
 * The contract test.
 *
 * It is generated from the contract's example — the same example the frontend's
 * mock is built from. That is the point: when this passes, the two sides agree.
 *
 * Replace `notMapConfig` with your real handler as soon as you have one. Until
 * then this test fails, which is exactly what a to-do looks like in code.
 */
const EXAMPLE_INPUT = {} as any;

test('map.config matches its contract example', async () => {
  const result = await notMapConfig(EXAMPLE_INPUT);
  assert.equal(typeof result, 'object', 'output should be an object');
  const first = result as any;
  assert.ok("tileUrl" in first, 'missing required output field: tileUrl');
  assert.ok("defaultCenterLat" in first, 'missing required output field: defaultCenterLat');
  assert.ok("defaultCenterLng" in first, 'missing required output field: defaultCenterLng');
  assert.ok("defaultZoom" in first, 'missing required output field: defaultZoom');
});
