// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  markers.list@1.0.0
// spec-hash: sha256:cee8e41453f94899f75fd9127f87c5dce6cc95a4181d446b7ee717f365c37434
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:2eb07076eebad5b2f3117d634c945da2fd6984166d64973c529d200763b769f2
// ─────────────────────────────────────────────────────────────────────────
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { notMarkersList } from '../routes/markers-list.js';

/**
 * The contract test.
 *
 * It is generated from the contract's example — the same example the frontend's
 * mock is built from. That is the point: when this passes, the two sides agree.
 *
 * Replace `notMarkersList` with your real handler as soon as you have one. Until
 * then this test fails, which is exactly what a to-do looks like in code.
 */
const EXAMPLE_INPUT = {
  "bbox": [
    1,
    2,
    3,
    4
  ],
  "since": "2026-01-01T09:02:00.000Z"
} as any;

test('markers.list matches its contract example', async () => {
  const result = await notMarkersList(EXAMPLE_INPUT);
  assert.ok(Array.isArray(result), 'output should be an array');
  const first = (result as any[])[0] ?? {};
  assert.ok("id" in first, 'missing required output field: id');
  assert.ok("lat" in first, 'missing required output field: lat');
  assert.ok("lng" in first, 'missing required output field: lng');
  assert.ok("label" in first, 'missing required output field: label');
  assert.ok("kind" in first, 'missing required output field: kind');
  assert.ok("updatedAt" in first, 'missing required output field: updatedAt');
});
