// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  markers.detail@1.0.0
// spec-hash: sha256:1c1d5d62cf22b3a650e946eda57d4c7ac000e08a101035b5d2f9e48cadac8a6e
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:e1d4d5a64facb9f99df67ece84dbc4560ae213984bef2993de6ec5ffc375fcc5
// ─────────────────────────────────────────────────────────────────────────
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { notMarkersDetail } from '../routes/markers-detail.js';

/**
 * The contract test.
 *
 * It is generated from the contract's example — the same example the frontend's
 * mock is built from. That is the point: when this passes, the two sides agree.
 *
 * Replace `notMarkersDetail` with your real handler as soon as you have one. Until
 * then this test fails, which is exactly what a to-do looks like in code.
 */
const EXAMPLE_INPUT = {
  "id": "id_101"
} as any;

test('markers.detail matches its contract example', async () => {
  const result = await notMarkersDetail(EXAMPLE_INPUT);
  assert.equal(typeof result, 'object', 'output should be an object');
  const first = result as any;
  assert.ok("id" in first, 'missing required output field: id');
  assert.ok("label" in first, 'missing required output field: label');
  assert.ok("kind" in first, 'missing required output field: kind');
  assert.ok("lastSeenAt" in first, 'missing required output field: lastSeenAt');
});
