// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  positions.ingest@1.0.0
// spec-hash: sha256:99c3eef72ebb94502d1455a5a35409549921a9365df71c3bbbc3fd7659ca256e
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:aa9e9be2d4f9e4545b9e92790081f80757a30622b073ce452f11e9fa1ee1227a
// ─────────────────────────────────────────────────────────────────────────
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { notPositionsIngest } from '../routes/positions-ingest.js';

/**
 * The contract test.
 *
 * It is generated from the contract's example — the same example the frontend's
 * mock is built from. That is the point: when this passes, the two sides agree.
 *
 * Replace `notPositionsIngest` with your real handler as soon as you have one. Until
 * then this test fails, which is exactly what a to-do looks like in code.
 */
const EXAMPLE_INPUT = {
  "deviceId": "dev_101",
  "lat": 12.92,
  "lng": 12.93,
  "at": "2026-01-01T09:04:00.000Z"
} as any;

test('positions.ingest matches its contract example', async () => {
  const result = await notPositionsIngest(EXAMPLE_INPUT);
  assert.equal(typeof result, 'object', 'output should be an object');
  const first = result as any;
  assert.ok("accepted" in first, 'missing required output field: accepted');
});
