# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# contract:  positions.ingest@1.0.0
# spec-hash: sha256:99c3eef72ebb94502d1455a5a35409549921a9365df71c3bbbc3fd7659ca256e
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:8a0655af9235b019230417ed3393249c27a9e756b480a6a9b23d4f92899c2ecc
# ─────────────────────────────────────────────────────────────────────────
import pytest

from ..routers import positions_ingest as route

# Generated from the contract's example — the same one the frontend mocks.
EXAMPLE_INPUT = {
    "device_id": "dev_101",
    "lat": 12.92,
    "lng": 12.93,
    "at": "2026-01-01T09:04:00.000Z"
}


@pytest.mark.asyncio
async def test_positions_ingest_matches_contract() -> None:
    result = await route.positions_ingest(EXAMPLE_INPUT)
    first = result
    assert hasattr(first, "accepted") or "accepted" in first
