# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# contract:  app.config@1.0.0
# spec-hash: sha256:5aaf7ac1d1d4ffc3ae6a277691a6562fe3db38f309b0a1dcf1fe89b950e0ec54
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:965e5ed99b5f5eeab19e0247a89f6157de82d7f1adb7a65ed6878f272efda431
# ─────────────────────────────────────────────────────────────────────────
import pytest

from ..routers import app_config as route

# Generated from the contract's example — the same one the frontend mocks.
EXAMPLE_INPUT = {}


@pytest.mark.asyncio
async def test_app_config_matches_contract() -> None:
    result = await route.app_config(EXAMPLE_INPUT)
    first = result
    assert hasattr(first, "app_name") or "app_name" in first
    assert hasattr(first, "api_base_url") or "api_base_url" in first
