# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# contract:  markers.detail@1.0.0
# spec-hash: sha256:1c1d5d62cf22b3a650e946eda57d4c7ac000e08a101035b5d2f9e48cadac8a6e
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:b9dc3001dc7a612130ea0994969548eda77955637ace1d5196c94b02e5a0948c
# ─────────────────────────────────────────────────────────────────────────
import pytest

from ..routers import markers_detail as route

# Generated from the contract's example — the same one the frontend mocks.
EXAMPLE_INPUT = {
    "id": "id_101"
}


@pytest.mark.asyncio
async def test_markers_detail_matches_contract() -> None:
    result = await route.markers_detail(EXAMPLE_INPUT)
    first = result
    assert hasattr(first, "id") or "id" in first
    assert hasattr(first, "label") or "label" in first
    assert hasattr(first, "kind") or "kind" in first
    assert hasattr(first, "last_seen_at") or "last_seen_at" in first
