# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# contract:  map.config@1.0.0
# spec-hash: sha256:1e9307a37a257a642479feb77c66f42e762df381247040bc31255214cf5af39f
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:6051677f1f960edeba545a1d4b7a1cb4ae69f415b60a1bb567ea1d8437d951f0
# ─────────────────────────────────────────────────────────────────────────
import pytest

from ..routers import map_config as route

# Generated from the contract's example — the same one the frontend mocks.
EXAMPLE_INPUT = {}


@pytest.mark.asyncio
async def test_map_config_matches_contract() -> None:
    result = await route.map_config(EXAMPLE_INPUT)
    first = result
    assert hasattr(first, "tile_url") or "tile_url" in first
    assert hasattr(first, "default_center_lat") or "default_center_lat" in first
    assert hasattr(first, "default_center_lng") or "default_center_lng" in first
    assert hasattr(first, "default_zoom") or "default_zoom" in first
