# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# contract:  markers.list@1.0.0
# spec-hash: sha256:cee8e41453f94899f75fd9127f87c5dce6cc95a4181d446b7ee717f365c37434
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:37813ee784711e95bdb719cebaa1f4891e59844826c5dfd1068e704cef7241bb
# ─────────────────────────────────────────────────────────────────────────
import pytest

from ..routers import markers_list as route

# Generated from the contract's example — the same one the frontend mocks.
EXAMPLE_INPUT = {
    "bbox": [
        1,
        2,
        3,
        4
    ],
    "since": "2026-01-01T09:02:00.000Z"
}


@pytest.mark.asyncio
async def test_markers_list_matches_contract() -> None:
    result = await route.markers_list(EXAMPLE_INPUT)
    assert isinstance(result, list)
    first = result[0] if result else {}
    assert hasattr(first, "id") or "id" in first
    assert hasattr(first, "lat") or "lat" in first
    assert hasattr(first, "lng") or "lng" in first
    assert hasattr(first, "label") or "label" in first
    assert hasattr(first, "kind") or "kind" in first
    assert hasattr(first, "updated_at") or "updated_at" in first
