import type { GenContract } from './pack.js';
import { fieldsOf, unwrapArray } from './pack.js';

/**
 * OpenAPI is a projection, not the source of truth.
 *
 * The internal contract format is the source because it also covers `function`,
 * `event` and `type` boundaries, which OpenAPI cannot express. Exporting the
 * `http` subset gives you Swagger UI, Postman and interoperability for free
 * without giving up the other three kinds.
 */
export function toOpenApi(contracts: GenContract[], projectName: string) {
  const http = contracts.filter((c) => c.kind === 'http' || c.kind === 'config');
  const paths: Record<string, any> = {};
  const schemas: Record<string, any> = {};

  for (const c of contracts.filter((x) => x.kind === 'type')) {
    schemas[c.spec.transport.symbol || c.key] = cleanSchema(c.spec.output);
  }

  for (const c of http) {
    const path = (c.spec.transport.path || `/api/${c.key.replace(/\./g, '/')}`)
      .replace(/:([A-Za-z0-9_]+)/g, '{$1}');
    const method = (c.spec.transport.method || 'GET').toLowerCase();
    const pathParams = [...path.matchAll(/\{([A-Za-z0-9_]+)\}/g)].map((m) => m[1]);
    const inputs = fieldsOf(c.spec.input);
    const isRead = method === 'get' || method === 'delete';

    const parameters = inputs
      .filter((f) => pathParams.includes(f.name) || isRead)
      .map((f) => ({
        name: f.name,
        in: pathParams.includes(f.name) ? 'path' : 'query',
        required: pathParams.includes(f.name) ? true : f.required,
        schema: cleanSchema(f.prop),
        description: f.prop.description ?? undefined,
      }));

    const bodyFields = inputs.filter((f) => !pathParams.includes(f.name) && !isRead);

    const responses: Record<string, any> = {
      '200': {
        description: 'Success',
        content: { 'application/json': { schema: cleanSchema(c.spec.output), examples: examplesFor(c) } },
      },
    };
    for (const err of c.spec.errors) {
      responses[String(err.http)] = {
        description: `${err.code}${err.when ? ` — ${err.when}` : ''}`,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: { code: { type: 'string', enum: [err.code] }, message: { type: 'string' } },
              required: ['code'],
            },
          },
        },
      };
    }

    paths[path] ??= {};
    paths[path][method] = {
      operationId: c.key.replace(/\./g, '_'),
      summary: c.spec.summary || c.key,
      description: `SparkX contract ${c.key}@${c.semver} (${c.state}). Spec hash ${c.hash}.`,
      tags: [c.key.split('.')[0]],
      ...(parameters.length ? { parameters } : {}),
      ...(bodyFields.length
        ? {
          requestBody: {
            required: bodyFields.some((f) => f.required),
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: Object.fromEntries(bodyFields.map((f) => [f.name, cleanSchema(f.prop)])),
                  required: bodyFields.filter((f) => f.required).map((f) => f.name),
                },
              },
            },
          },
        }
        : {}),
      responses,
    };
  }

  return {
    openapi: '3.1.0',
    info: {
      title: `${projectName} API`,
      version: '1.0.0',
      description:
        'Generated by SparkX from its internal contract format. This document covers the http contracts only — function, event and type contracts have no OpenAPI representation and live in .spark/contracts/.',
    },
    paths,
    ...(Object.keys(schemas).length ? { components: { schemas } } : {}),
  };
}

function examplesFor(c: GenContract) {
  if (c.examples.length === 0) return undefined;
  return Object.fromEntries(
    c.examples.map((ex, i) => [`example${i + 1}`, { value: ex.output }]),
  );
}

/** Removes anything that is ours rather than OpenAPI's. */
function cleanSchema(node: any): any {
  if (Array.isArray(node)) return node.map(cleanSchema);
  if (!node || typeof node !== 'object') return node;
  const out: any = {};
  for (const [k, v] of Object.entries(node)) {
    if (k === '$schema') continue;
    out[k] = cleanSchema(v);
  }
  return out;
}
