import { createHash } from 'node:crypto';
import type { ContractSpec, ContractExample } from '../contracts/spec.js';

/**
 * The language pack interface.
 *
 * Adding Spring Boot, Go or Flutter support must never require editing SparkX
 * core — it is a new file in ./packs and one line in ./index.ts. Getting this
 * boundary right in v1 matters more than how many packs v1 ships with.
 */

export interface GenContract {
  key: string;
  kind: ContractSpec['kind'];
  semver: string;
  state: string;
  spec: ContractSpec;
  examples: ContractExample[];
  hash: string;
}

export interface GenFile {
  path: string;
  content: string;
}

export interface LanguagePack {
  id: string;
  label: string;
  lane: 'frontend' | 'backend' | 'both';
  /** Shared data shapes, emitted once for the whole contract set. */
  emitTypes(contracts: GenContract[]): GenFile[];
  /** The consumer side: what the caller imports. */
  emitClient(c: GenContract): GenFile[];
  /** The provider side: the skeleton whose job is to make the test pass. */
  emitServerStub(c: GenContract): GenFile[];
  /** Mock data derived from the contract's examples. */
  emitMocks(c: GenContract): GenFile[];
  /** A test asserting the implementation matches the examples. */
  emitContractTest(c: GenContract): GenFile[];
  /** Files that are the same for every project using this pack. */
  emitRuntime(): GenFile[];
}

// ── banners ──────────────────────────────────────────────────────────────────

const sha = (s: string) => 'sha256:' + createHash('sha256').update(s).digest('hex');

export const BODY_MARKER = 'spark-body:';

/**
 * Every generated file carries its contract identity and a hash of its own body.
 *
 * The body hash is what makes GENERATED_EDITED detectable: the checker
 * recomputes it and compares. That is the whole mechanism — no file watching,
 * no daemon.
 */
export function banner(comment: '//' | '#', meta: {
  contract?: string; semver?: string; specHash?: string; note?: string;
}, body: string): string {
  const lines = [
    `${comment} ─────────────────────────────────────────────────────────────────────────`,
    `${comment} Generated by SparkX. Do not edit this file.`,
  ];
  if (meta.contract) lines.push(`${comment} contract:  ${meta.contract}@${meta.semver ?? '?'}`);
  if (meta.specHash) lines.push(`${comment} spec-hash: ${meta.specHash}`);
  if (meta.note) lines.push(`${comment} ${meta.note}`);
  lines.push(
    `${comment} Change the contract in SparkX and regenerate. Handwritten edits here are`,
    `${comment} reported as GENERATED_EDITED and will be overwritten.`,
    `${comment} ${BODY_MARKER} ${sha(body)}`,
    `${comment} ─────────────────────────────────────────────────────────────────────────`,
    '',
  );
  return lines.join('\n') + body;
}

/** Recovers {declaredHash, actualHash} from a generated file on disk. */
export function readBanner(content: string): { declared: string; actual: string } | null {
  const lines = content.split('\n');
  const idx = lines.findIndex((l) => l.includes(BODY_MARKER));
  if (idx === -1) return null;
  const declared = lines[idx].split(BODY_MARKER)[1].trim();
  // After the hash line comes the closing rule, and the body starts immediately
  // after it — `banner()` joins its lines with a trailing newline, then appends
  // the body with nothing in between.
  const body = lines.slice(idx + 2).join('\n');
  return { declared, actual: sha(body) };
}

// ── schema → language types ──────────────────────────────────────────────────

type Node = Record<string, any>;

export function unwrapArray(schema: Node): { inner: Node; isArray: boolean } {
  if (schema?.type === 'array') return { inner: schema.items ?? {}, isArray: true };
  return { inner: schema ?? {}, isArray: false };
}

export function tsScalar(prop: Node): string {
  if (!prop) return 'unknown';
  if (prop.type === 'array') return `${tsScalar(prop.items ?? {})}[]`;
  switch (prop.type) {
    case 'number': case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'object': return 'Record<string, unknown>';
    default: return 'string';
  }
}

export function pyScalar(prop: Node): string {
  if (!prop) return 'Any';
  if (prop.type === 'array') return `List[${pyScalar(prop.items ?? {})}]`;
  switch (prop.type) {
    case 'number': return 'float';
    case 'integer': return 'int';
    case 'boolean': return 'bool';
    case 'object': return 'Dict[str, Any]';
    default: return 'str';
  }
}

export function fieldsOf(schema: Node): { name: string; prop: Node; required: boolean }[] {
  const { inner } = unwrapArray(schema ?? {});
  const props = (inner.properties ?? {}) as Record<string, Node>;
  const required = new Set<string>(inner.required ?? []);
  return Object.entries(props).map(([name, prop]) => ({ name, prop, required: required.has(name) }));
}

export function tsInterfaceBody(schema: Node, indent = '  '): string {
  const fields = fieldsOf(schema);
  if (fields.length === 0) return `${indent}[key: string]: unknown;`;
  return fields
    .map(({ name, prop, required }) => {
      const doc = prop.description ? `${indent}/** ${prop.description} */\n` : '';
      return `${doc}${indent}${safeKey(name)}${required ? '' : '?'}: ${tsScalar(prop)};`;
    })
    .join('\n');
}

export const safeKey = (name: string): string =>
  /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);

/** `/api/markers/:id` → a template literal and the list of path params. */
export function pathParts(path: string): { params: string[]; template: string } {
  const params: string[] = [];
  const template = path.replace(/:([A-Za-z0-9_]+)/g, (_, p) => {
    params.push(p);
    return `\${encodeURIComponent(String(args.${p}))}`;
  });
  return { params, template };
}
