// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// Shared runtime for every generated client.
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:05a27eac971550fb7f7b6e4b22f49af3bac78c731919dbd0a044eb3df2cd4914
// ─────────────────────────────────────────────────────────────────────────
export interface SparkConfig {
  /** Where the backend lives. Point this at your API in one place. */
  baseUrl: string;
  /** Contract keys to serve from their examples instead of the network. */
  mock: 'all' | 'none' | string[];
  /** Extra headers on every request — auth token, tracing, whatever. */
  headers: () => Record<string, string>;
}

export const sparkConfig: SparkConfig = {
  baseUrl: '',
  mock: 'all',
  headers: () => ({}),
};

/** True while a contract should be served from its example data. */
export function isMocked(contractKey: string): boolean {
  const m = sparkConfig.mock;
  if (m === 'all') return true;
  if (m === 'none') return false;
  return m.includes(contractKey);
}

/** Every error a generated client throws. `code` is the contract's own error code. */
export class SparkError extends Error {
  constructor(
    readonly code: string,
    readonly status: number,
    readonly contract: string,
    message?: string,
  ) {
    super(message ?? `${contract} failed with ${code}`);
    this.name = 'SparkError';
  }
}

export async function sparkFetch<T>(
  contract: string,
  method: string,
  path: string,
  body?: unknown,
  query?: Record<string, unknown>,
): Promise<T> {
  const url = new URL(sparkConfig.baseUrl + path, sparkConfig.baseUrl || window.location.origin);
  for (const [k, v] of Object.entries(query ?? {})) {
    if (v === undefined || v === null) continue;
    url.searchParams.set(k, Array.isArray(v) ? v.join(',') : String(v));
  }

  const res = await fetch(url.toString(), {
    method,
    headers: { 'Content-Type': 'application/json', ...sparkConfig.headers() },
    body: body === undefined ? undefined : JSON.stringify(body),
  });

  if (!res.ok) {
    let code = 'UNKNOWN';
    let message: string | undefined;
    try {
      const err = await res.json() as { code?: string; message?: string };
      code = err.code ?? code;
      message = err.message;
    } catch { /* a non-JSON error body is still an error */ }
    throw new SparkError(code, res.status, contract, message);
  }

  return await res.json() as T;
}

type Handler<T> = (event: T) => void;

/**
 * Subscribes to a server-pushed event contract.
 *
 * While mocked it replays the contract's example once a second, so a live view
 * can be built and demoed before any websocket exists.
 */
export function sparkSubscribe<T>(
  contract: string,
  channel: string,
  handler: Handler<T>,
  mockEvent?: T,
): () => void {
  if (isMocked(contract)) {
    if (mockEvent === undefined) return () => {};
    const timer = setInterval(() => handler(structuredClone(mockEvent)), 1000);
    return () => clearInterval(timer);
  }

  const wsUrl = (sparkConfig.baseUrl || window.location.origin)
    .replace(/^http/, 'ws') + '/ws';
  const socket = new WebSocket(wsUrl);
  socket.addEventListener('open', () => socket.send(JSON.stringify({ subscribe: channel })));
  socket.addEventListener('message', (e) => {
    try {
      const msg = JSON.parse(e.data as string) as { channel?: string; payload?: T };
      if (msg.channel === channel && msg.payload !== undefined) handler(msg.payload);
    } catch { /* ignore frames we do not understand */ }
  });
  return () => socket.close();
}
