// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// Every shared shape in this project.
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:ec50543eeb2e12feddac58e715692915e9591c38475c644fe02b8da9293a2bed
// ─────────────────────────────────────────────────────────────────────────
/** One thing shown on the map. — contract Marker@1.0.0 */
export interface Marker {
  id: string;
  lat: number;
  lng: number;
  label: string;
  kind: string;
  headingDeg?: number;
  updatedAt: string;
}

export interface AppConfigOutput {
  appName: string;
  apiBaseUrl: string;
  features?: string[];
}

export interface MapConfigOutput {
  /** XYZ tile template */
  tileUrl: string;
  defaultCenterLat: number;
  defaultCenterLng: number;
  defaultZoom: number;
  maxZoom?: number;
}

export interface MapViewportOutput {
  bbox: number[];
  zoom: number;
  centerLat: number;
  centerLng: number;
}

/** Input for markers.detail@1.0.0 */
export interface MarkersDetailInput {
  id: string;
}

export interface MarkersDetailOutput {
  id: string;
  label: string;
  kind: string;
  speedKph?: number;
  lastSeenAt: string;
  /** recent positions */
  history?: Record<string, unknown>[];
}

/** Error codes markers.detail can produce. */
export type MarkersDetailError = "MARKER_NOT_FOUND";

/** Input for markers.list@1.0.0 */
export interface MarkersListInput {
  /** west, south, east, north */
  bbox: number[];
  /** only markers updated after this instant */
  since?: string;
}

export interface MarkersListItem {
  id: string;
  lat: number;
  lng: number;
  label: string;
  kind: string;
  updatedAt: string;
}

export type MarkersListOutput = MarkersListItem[];

/** Error codes markers.list can produce. */
export type MarkersListError = "BBOX_INVALID";

export interface MarkersStreamOutput {
  id: string;
  lat: number;
  lng: number;
  headingDeg?: number;
  at: string;
}

/** Input for positions.ingest@1.0.0 */
export interface PositionsIngestInput {
  deviceId: string;
  lat: number;
  lng: number;
  headingDeg?: number;
  at: string;
}

export interface PositionsIngestOutput {
  accepted: number;
}

/** Error codes positions.ingest can produce. */
export type PositionsIngestError = "COORDS_INVALID";

/** Input for positions.store@1.0.0 */
export interface PositionsStoreInput {
  deviceId: string;
  lat: number;
  lng: number;
  at: string;
}

export interface PositionsStoreOutput {
  written: boolean;
}

/** Every error code in this project, in one place. */
export const SPARK_ERROR_CODES = [
  "BBOX_INVALID",
  "COORDS_INVALID",
  "MARKER_NOT_FOUND",
] as const;
export type SparkErrorCode = typeof SPARK_ERROR_CODES[number];
