# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# Every contract shape as a Pydantic model.
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:7570d98fbd7f3161555d645f3772dd1566e86efde7999da9897e8be29360b6ad
# ─────────────────────────────────────────────────────────────────────────
from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class Marker(BaseModel):
    id: str
    lat: float
    lng: float
    label: str
    kind: str
    heading_deg: Optional[float] = None
    updated_at: str


class AppConfigOutput(BaseModel):
    app_name: str
    api_base_url: str
    features: Optional[List[str]] = None


class MapConfigOutput(BaseModel):
    tile_url: str  # XYZ tile template
    default_center_lat: float
    default_center_lng: float
    default_zoom: float
    max_zoom: Optional[float] = None


class MapViewportOutput(BaseModel):
    bbox: List[float]
    zoom: float
    center_lat: float
    center_lng: float


class MarkersDetailInput(BaseModel):
    id: str


class MarkersDetailOutput(BaseModel):
    id: str
    label: str
    kind: str
    speed_kph: Optional[float] = None
    last_seen_at: str
    history: Optional[List[Dict[str, Any]]] = None  # recent positions


class MarkersListInput(BaseModel):
    bbox: List[float]  # west, south, east, north
    since: Optional[str] = None  # only markers updated after this instant


class MarkersListItem(BaseModel):
    id: str
    lat: float
    lng: float
    label: str
    kind: str
    updated_at: str


MarkersListOutput = List[MarkersListItem]


class MarkersStreamOutput(BaseModel):
    id: str
    lat: float
    lng: float
    heading_deg: Optional[float] = None
    at: str


class PositionsIngestInput(BaseModel):
    device_id: str
    lat: float
    lng: float
    heading_deg: Optional[float] = None
    at: str


class PositionsIngestOutput(BaseModel):
    accepted: float


class PositionsStoreInput(BaseModel):
    device_id: str
    lat: float
    lng: float
    at: str


class PositionsStoreOutput(BaseModel):
    written: bool
