// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// Shared runtime for every generated route.
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:31b8fea9960bfeb2a827e691b69ec276ab1264657af009f36060f2c11775017b
// ─────────────────────────────────────────────────────────────────────────
import type { Request, Response, NextFunction } from 'express';

/** Thrown by every un-implemented handler. Seeing this in production is a bug. */
export class NotImplemented extends Error {
  constructor(readonly contract: string) {
    super(`${contract} is not implemented yet`);
    this.name = 'NotImplemented';
  }
}

/** An error the contract declares. Anything else is a 500 and your fault. */
export class ContractError extends Error {
  constructor(readonly code: string, readonly status: number, message?: string) {
    super(message ?? code);
    this.name = 'ContractError';
  }
}

export interface FieldRule {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'array' | 'object';
  required: boolean;
}

/**
 * Validates one request against a contract's input schema.
 *
 * Deliberately dependency-free — a generated file should never force a library
 * choice on the project it lands in.
 */
export function validate(rules: FieldRule[], source: Record<string, unknown>): string[] {
  const problems: string[] = [];
  for (const rule of rules) {
    const value = source[rule.name];
    if (value === undefined || value === null || value === '') {
      if (rule.required) problems.push(`${rule.name} is required`);
      continue;
    }
    const actual = Array.isArray(value) ? 'array' : typeof value;
    if (rule.type === 'number' && actual === 'string' && !Number.isNaN(Number(value))) continue;
    if (rule.type === 'boolean' && (value === 'true' || value === 'false')) continue;
    if (rule.type === 'array' && actual === 'string') continue; // comma-joined query param
    if (actual !== rule.type) {
      problems.push(`${rule.name} should be ${rule.type}, got ${actual}`);
    }
  }
  return problems;
}

/** Express error shape every generated route uses, so clients see one format. */
export function sendError(res: Response, code: string, status: number, message?: string): void {
  res.status(status).json({ code, message: message ?? code });
}

export function wrap(
  contract: string,
  handler: (req: Request, res: Response) => Promise<void>,
) {
  return async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      await handler(req, res);
    } catch (err) {
      if (err instanceof ContractError) return sendError(res, err.code, err.status, err.message);
      if (err instanceof NotImplemented) return sendError(res, 'NOT_IMPLEMENTED', 501, err.message);
      next(err);
    }
  };
}
