# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# Shared runtime for every generated router.
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:d7048a01c1bb8894f76883b2e37236448375766285c1001a99878e036e651de1
# ─────────────────────────────────────────────────────────────────────────
from fastapi import HTTPException


class NotImplementedContract(HTTPException):
    """Raised by every un-implemented handler."""

    def __init__(self, contract: str) -> None:
        super().__init__(status_code=501, detail={"code": "NOT_IMPLEMENTED", "message": f"{contract} is not implemented yet"})


class ContractError(HTTPException):
    """An error the contract declares. Anything else is a 500 and your bug."""

    def __init__(self, code: str, status: int, message: str | None = None) -> None:
        super().__init__(status_code=status, detail={"code": code, "message": message or code})
