// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// Server-side view of every contract shape.
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:040e7ba6f3c1eb363cd03b6e9ad337f29ff8f319169a466dd09761531baff60e
// ─────────────────────────────────────────────────────────────────────────
export interface Marker {
  id: string;
  lat: number;
  lng: number;
  label: string;
  kind: string;
  headingDeg?: number;
  updatedAt: string;
}

export interface AppConfigOutput {
  appName: string;
  apiBaseUrl: string;
  features?: string[];
}

export interface MapConfigOutput {
  /** XYZ tile template */
  tileUrl: string;
  defaultCenterLat: number;
  defaultCenterLng: number;
  defaultZoom: number;
  maxZoom?: number;
}

export interface MapViewportOutput {
  bbox: number[];
  zoom: number;
  centerLat: number;
  centerLng: number;
}

export interface MarkersDetailInput {
  id: string;
}

export interface MarkersDetailOutput {
  id: string;
  label: string;
  kind: string;
  speedKph?: number;
  lastSeenAt: string;
  /** recent positions */
  history?: Record<string, unknown>[];
}

export interface MarkersListInput {
  /** west, south, east, north */
  bbox: number[];
  /** only markers updated after this instant */
  since?: string;
}

export interface MarkersListItem {
  id: string;
  lat: number;
  lng: number;
  label: string;
  kind: string;
  updatedAt: string;
}

export type MarkersListOutput = MarkersListItem[];

export interface MarkersStreamOutput {
  id: string;
  lat: number;
  lng: number;
  headingDeg?: number;
  at: string;
}

export interface PositionsIngestInput {
  deviceId: string;
  lat: number;
  lng: number;
  headingDeg?: number;
  at: string;
}

export interface PositionsIngestOutput {
  accepted: number;
}

export interface PositionsStoreInput {
  deviceId: string;
  lat: number;
  lng: number;
  at: string;
}

export interface PositionsStoreOutput {
  written: boolean;
}
