// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  app.config@1.0.0
// spec-hash: sha256:5aaf7ac1d1d4ffc3ae6a277691a6562fe3db38f309b0a1dcf1fe89b950e0ec54
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:bae3316391f0ea0cc99044f757de5ac62cd7cfc4c8027c7f5bd3c6d575788bff
// ─────────────────────────────────────────────────────────────────────────
import { Router } from 'express';
import { NotImplemented, validate, sendError, wrap, type FieldRule } from '../runtime.js';
import type * as T from '../types.js';

/** Runtime settings the client needs before it can render anything. — GET /api/app/config */
export type AppConfigHandler = () => Promise<T.AppConfigOutput>;

const RULES: FieldRule[] = [];

/** The default implementation. Replacing this is the whole job. */
export const notAppConfig: AppConfigHandler = async () => {
  throw new NotImplemented("app.config");
};

export function appConfigRouter(impl: AppConfigHandler = notAppConfig): Router {
  const router = Router();

  router.get("/api/app/config", wrap("app.config", async (req, res) => {
    const input = { ...req.params, ...req.query } as Record<string, unknown>;
    const problems = validate(RULES, input);
    if (problems.length > 0) {
      return sendError(res, "INPUT_INVALID", 400, problems.join('; '));
    }
    const result = await impl();
    res.json(result);
  }));

  return router;
}

/* Error codes this contract is allowed to return:
 *   (none declared)
 * Anything else reaching the client is a bug, not a contract.
 */
