// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// Route registry.
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:f0de5062e77c75e6db34320ddff804ee58c5f0611e841de5c8cd65d7e4a64313
// ─────────────────────────────────────────────────────────────────────────
import type { Express } from 'express';
import { appConfigRouter } from './app-config.js';
import { mapConfigRouter } from './map-config.js';
import { markersDetailRouter } from './markers-detail.js';
import { markersListRouter } from './markers-list.js';
import { positionsIngestRouter } from './positions-ingest.js';

/**
 * Mounts every contract route.
 *
 * Pass real handlers in as you build them:
 *
 *   registerSparkRoutes(app, { appConfig: myHandler });
 */
export function registerSparkRoutes(
  app: Express,
  impls: Partial<{
    appConfig: Parameters<typeof appConfigRouter>[0];
    mapConfig: Parameters<typeof mapConfigRouter>[0];
    markersDetail: Parameters<typeof markersDetailRouter>[0];
    markersList: Parameters<typeof markersListRouter>[0];
    positionsIngest: Parameters<typeof positionsIngestRouter>[0];
  }> = {},
): void {
  app.use(appConfigRouter(impls.appConfig));
  app.use(mapConfigRouter(impls.mapConfig));
  app.use(markersDetailRouter(impls.markersDetail));
  app.use(markersListRouter(impls.markersList));
  app.use(positionsIngestRouter(impls.positionsIngest));
}
