// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  map.config@1.0.0
// spec-hash: sha256:1e9307a37a257a642479feb77c66f42e762df381247040bc31255214cf5af39f
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:131b3c06bf5bc94e1ac12e4f34f91cc1f57048def64cc57430777ce3d85406da
// ─────────────────────────────────────────────────────────────────────────
import { Router } from 'express';
import { NotImplemented, validate, sendError, wrap, type FieldRule } from '../runtime.js';
import type * as T from '../types.js';

/** Tile provider and default viewport, served once at startup. — GET /api/map/config */
export type MapConfigHandler = () => Promise<T.MapConfigOutput>;

const RULES: FieldRule[] = [];

/** The default implementation. Replacing this is the whole job. */
export const notMapConfig: MapConfigHandler = async () => {
  throw new NotImplemented("map.config");
};

export function mapConfigRouter(impl: MapConfigHandler = notMapConfig): Router {
  const router = Router();

  router.get("/api/map/config", wrap("map.config", async (req, res) => {
    const input = { ...req.params, ...req.query } as Record<string, unknown>;
    const problems = validate(RULES, input);
    if (problems.length > 0) {
      return sendError(res, "INPUT_INVALID", 400, problems.join('; '));
    }
    const result = await impl();
    res.json(result);
  }));

  return router;
}

/* Error codes this contract is allowed to return:
 *   (none declared)
 * Anything else reaching the client is a bug, not a contract.
 */
