// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  markers.detail@1.0.0
// spec-hash: sha256:1c1d5d62cf22b3a650e946eda57d4c7ac000e08a101035b5d2f9e48cadac8a6e
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:049348853517936fd69d84a8d0e102bdb10e6b5f4ef8f7b81553d4408514ec9a
// ─────────────────────────────────────────────────────────────────────────
import { Router } from 'express';
import { NotImplemented, validate, sendError, wrap, type FieldRule } from '../runtime.js';
import type * as T from '../types.js';

/** Full detail for one marker, loaded on tap. — GET /api/markers/:id */
export type MarkersDetailHandler = (args: T.MarkersDetailInput) => Promise<T.MarkersDetailOutput>;

const RULES: FieldRule[] = [
  {
    "name": "id",
    "type": "string",
    "required": true
  }
];

/** The default implementation. Replacing this is the whole job. */
export const notMarkersDetail: MarkersDetailHandler = async (_args) => {
  throw new NotImplemented("markers.detail");
};

export function markersDetailRouter(impl: MarkersDetailHandler = notMarkersDetail): Router {
  const router = Router();

  router.get("/api/markers/:id", wrap("markers.detail", async (req, res) => {
    const input = { ...req.params, ...req.query } as Record<string, unknown>;
    const problems = validate(RULES, input);
    if (problems.length > 0) {
      return sendError(res, "MARKER_NOT_FOUND", 400, problems.join('; '));
    }
    const result = await impl(input as unknown as T.MarkersDetailInput);
    res.json(result);
  }));

  return router;
}

/* Error codes this contract is allowed to return:
 *   MARKER_NOT_FOUND (404) — no marker with that id
 * Anything else reaching the client is a bug, not a contract.
 */
