// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  markers.stream@1.0.0
// spec-hash: sha256:9f7c6d8099a6e19e48448dd10672c0b631d0ae81c57ce2eb4ffbec602b5763f6
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:62b900771f137ba5ec32976ea06ccb6e8f517658f5da53c3d1f20a20d3cb8cb6
// ─────────────────────────────────────────────────────────────────────────
import { NotImplemented } from '../runtime.js';
import type * as T from '../types.js';

/**
 * Movement events pushed to every client watching that area.
 *
 * Server-pushed. Call `publishMarkersStream` wherever the event actually happens;
 * the transport (websocket, SSE, pub/sub) is your choice — this file only
 * fixes the payload shape and the channel name.
 */
export const markersStreamChannel = "marker.moved";

export type MarkersStreamPublisher = (payload: T.MarkersStreamOutput) => void | Promise<void>;

let publisher: MarkersStreamPublisher | null = null;

export function registerMarkersStreamPublisher(p: MarkersStreamPublisher): void {
  publisher = p;
}

export async function publishMarkersStream(payload: T.MarkersStreamOutput): Promise<void> {
  if (!publisher) throw new NotImplemented("markers.stream");
  await publisher(payload);
}
