// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  markers.list@1.0.0
// spec-hash: sha256:cee8e41453f94899f75fd9127f87c5dce6cc95a4181d446b7ee717f365c37434
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:0fd0bcb063f95bb34a0f27cf5e032f25e2226558d5829befa6313803a90003e9
// ─────────────────────────────────────────────────────────────────────────
import { Router } from 'express';
import { NotImplemented, validate, sendError, wrap, type FieldRule } from '../runtime.js';
import type * as T from '../types.js';

/** Markers currently inside the visible bounding box. — GET /api/markers */
export type MarkersListHandler = (args: T.MarkersListInput) => Promise<T.MarkersListOutput>;

const RULES: FieldRule[] = [
  {
    "name": "bbox",
    "type": "array",
    "required": true
  },
  {
    "name": "since",
    "type": "string",
    "required": false
  }
];

/** The default implementation. Replacing this is the whole job. */
export const notMarkersList: MarkersListHandler = async (_args) => {
  throw new NotImplemented("markers.list");
};

export function markersListRouter(impl: MarkersListHandler = notMarkersList): Router {
  const router = Router();

  router.get("/api/markers", wrap("markers.list", async (req, res) => {
    const input = { ...req.params, ...req.query } as Record<string, unknown>;
    const problems = validate(RULES, input);
    if (problems.length > 0) {
      return sendError(res, "BBOX_INVALID", 400, problems.join('; '));
    }
    const result = await impl(input as unknown as T.MarkersListInput);
    res.json(result);
  }));

  return router;
}

/* Error codes this contract is allowed to return:
 *   BBOX_INVALID (400) — bbox is not [w,s,e,n]
 * Anything else reaching the client is a bug, not a contract.
 */
