// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  positions.ingest@1.0.0
// spec-hash: sha256:99c3eef72ebb94502d1455a5a35409549921a9365df71c3bbbc3fd7659ca256e
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:9c2cceff26db4d97ebcca87783fb38560e9059b16e9c1a2f8defe750614298e5
// ─────────────────────────────────────────────────────────────────────────
import { Router } from 'express';
import { NotImplemented, validate, sendError, wrap, type FieldRule } from '../runtime.js';
import type * as T from '../types.js';

/** A device or vehicle reporting where it is. — POST /api/positions */
export type PositionsIngestHandler = (args: T.PositionsIngestInput) => Promise<T.PositionsIngestOutput>;

const RULES: FieldRule[] = [
  {
    "name": "deviceId",
    "type": "string",
    "required": true
  },
  {
    "name": "lat",
    "type": "number",
    "required": true
  },
  {
    "name": "lng",
    "type": "number",
    "required": true
  },
  {
    "name": "headingDeg",
    "type": "number",
    "required": false
  },
  {
    "name": "at",
    "type": "string",
    "required": true
  }
];

/** The default implementation. Replacing this is the whole job. */
export const notPositionsIngest: PositionsIngestHandler = async (_args) => {
  throw new NotImplemented("positions.ingest");
};

export function positionsIngestRouter(impl: PositionsIngestHandler = notPositionsIngest): Router {
  const router = Router();

  router.post("/api/positions", wrap("positions.ingest", async (req, res) => {
    const input = { ...req.params, ...req.body } as Record<string, unknown>;
    const problems = validate(RULES, input);
    if (problems.length > 0) {
      return sendError(res, "COORDS_INVALID", 400, problems.join('; '));
    }
    const result = await impl(input as unknown as T.PositionsIngestInput);
    res.json(result);
  }));

  return router;
}

/* Error codes this contract is allowed to return:
 *   COORDS_INVALID (400) — lat/lng out of range
 * Anything else reaching the client is a bug, not a contract.
 */
