# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# contract:  app.config@1.0.0
# spec-hash: sha256:5aaf7ac1d1d4ffc3ae6a277691a6562fe3db38f309b0a1dcf1fe89b950e0ec54
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:a8bc60a4b6016b4cef5a090daa3d419134cae478d57835912a5ab55006bd6598
# ─────────────────────────────────────────────────────────────────────────
from typing import List

from fastapi import APIRouter

from .. import models
from ..runtime import NotImplementedContract

router = APIRouter()

CONTRACT = "app.config"

# Runtime settings the client needs before it can render anything.
# GET /api/app/config
#
# Error codes this contract may return:
#   (none declared)


@router.get("/api/app/config")
async def app_config() -> models.AppConfigOutput:
    raise NotImplementedContract(CONTRACT)
