# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# contract:  map.config@1.0.0
# spec-hash: sha256:1e9307a37a257a642479feb77c66f42e762df381247040bc31255214cf5af39f
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:9c891c6d89c8f77279bfffbfc32e43b3fa3f18a32e6af90b655c832c15c189cf
# ─────────────────────────────────────────────────────────────────────────
from typing import List

from fastapi import APIRouter

from .. import models
from ..runtime import NotImplementedContract

router = APIRouter()

CONTRACT = "map.config"

# Tile provider and default viewport, served once at startup.
# GET /api/map/config
#
# Error codes this contract may return:
#   (none declared)


@router.get("/api/map/config")
async def map_config() -> models.MapConfigOutput:
    raise NotImplementedContract(CONTRACT)
