# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# contract:  markers.list@1.0.0
# spec-hash: sha256:cee8e41453f94899f75fd9127f87c5dce6cc95a4181d446b7ee717f365c37434
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:813a6dee67bbaf6daa5dddec7ed673a3728d5006c9b1e16e320b0fbb2fdb753a
# ─────────────────────────────────────────────────────────────────────────
from typing import List

from fastapi import APIRouter

from .. import models
from ..runtime import NotImplementedContract

router = APIRouter()

CONTRACT = "markers.list"

# Markers currently inside the visible bounding box.
# GET /api/markers
#
# Error codes this contract may return:
#   BBOX_INVALID (400) — bbox is not [w,s,e,n]


@router.get("/api/markers")
async def markers_list(payload: models.MarkersListInput | None = None) -> List[models.MarkersListItem]:
    raise NotImplementedContract(CONTRACT)
