# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# contract:  markers.detail@1.0.0
# spec-hash: sha256:1c1d5d62cf22b3a650e946eda57d4c7ac000e08a101035b5d2f9e48cadac8a6e
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:be51299a532987241670cb0975b2b59ba897f339dcafbfbcfc9a3ea8fa4baa27
# ─────────────────────────────────────────────────────────────────────────
from typing import List

from fastapi import APIRouter

from .. import models
from ..runtime import NotImplementedContract

router = APIRouter()

CONTRACT = "markers.detail"

# Full detail for one marker, loaded on tap.
# GET /api/markers/{id}
#
# Error codes this contract may return:
#   MARKER_NOT_FOUND (404) — no marker with that id


@router.get("/api/markers/{id}")
async def markers_detail(payload: models.MarkersDetailInput | None = None) -> models.MarkersDetailOutput:
    raise NotImplementedContract(CONTRACT)
