# ─────────────────────────────────────────────────────────────────────────
# Generated by SparkX. Do not edit this file.
# contract:  positions.ingest@1.0.0
# spec-hash: sha256:99c3eef72ebb94502d1455a5a35409549921a9365df71c3bbbc3fd7659ca256e
# Change the contract in SparkX and regenerate. Handwritten edits here are
# reported as GENERATED_EDITED and will be overwritten.
# spark-body: sha256:77a4bbb138c64915896170dd38bc1fb4518528975e97922bd34d4adc39e26cb9
# ─────────────────────────────────────────────────────────────────────────
from typing import List

from fastapi import APIRouter

from .. import models
from ..runtime import NotImplementedContract

router = APIRouter()

CONTRACT = "positions.ingest"

# A device or vehicle reporting where it is.
# POST /api/positions
#
# Error codes this contract may return:
#   COORDS_INVALID (400) — lat/lng out of range


@router.post("/api/positions")
async def positions_ingest(payload: models.PositionsIngestInput | None = None) -> models.PositionsIngestOutput:
    raise NotImplementedContract(CONTRACT)
