// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  app.config@1.0.0
// spec-hash: sha256:5aaf7ac1d1d4ffc3ae6a277691a6562fe3db38f309b0a1dcf1fe89b950e0ec54
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:607b6b5c8c35f6106fec211f39d82ac09e425619906a348def6ee8426c9186b3
// ─────────────────────────────────────────────────────────────────────────
import { sparkFetch, isMocked } from '../runtime.js';
import type * as T from '../types.js';
import { appConfigMock } from '../mocks/app-config.js';

/**
 * Runtime settings the client needs before it can render anything.
 *
 * GET /api/app/config
 *
 */
export async function appConfig(): Promise<T.AppConfigOutput> {
  if (isMocked("app.config")) return structuredClone(appConfigMock);
  return sparkFetch<T.AppConfigOutput>(
    "app.config",
    "GET",
    `/api/app/config`,
    undefined,
    undefined,
  );
}
