// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// Client barrel.
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:962e53db87162aaea17bf625db71e62c8be5975cfc6903b29555c53d1ecc7b1d
// ─────────────────────────────────────────────────────────────────────────
import { appConfig } from './app-config.js';
import { mapConfig } from './map-config.js';
import { mapViewport } from './map-viewport.js';
import { markersDetail } from './markers-detail.js';
import { markersList } from './markers-list.js';
import { markersStream } from './markers-stream.js';
import { positionsIngest } from './positions-ingest.js';

export { appConfig } from './app-config.js';
export { mapConfig } from './map-config.js';
export { mapViewport } from './map-viewport.js';
export { markersDetail } from './markers-detail.js';
export { markersList } from './markers-list.js';
export { markersStream } from './markers-stream.js';
export { positionsIngest } from './positions-ingest.js';

/**
 * Every contract this project has, grouped by key.
 *
 *   const markers = await sparkClient.markers.list({ bbox });
 */
export const sparkClient = {
  app: {
    config: appConfig,
  },
  map: {
    config: mapConfig,
    viewport: mapViewport,
  },
  markers: {
    detail: markersDetail,
    list: markersList,
    stream: markersStream,
  },
  positions: {
    ingest: positionsIngest,
  },
};
