// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  map.viewport@1.0.0
// spec-hash: sha256:33ac56be56c8f3f39a6968383715d7b7a24a98721dad165e51c0bf29c6ad3860
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:8306ad3247b69ca3d8b3977c4b6b6cf59afa2f8051cc8ebf4dc0a8da99753b5d
// ─────────────────────────────────────────────────────────────────────────
import type * as T from '../types.js';
import { mapViewportMock } from '../mocks/map-viewport.js';

/**
 * Current viewport, published by the canvas to every layer above it.
 *
 * This is an in-lane boundary, not a network call: the module that provides it
 * lives in the same codebase. Import this type, build against `mapViewportMock`, and
 * swap in the real implementation when it lands.
 */
export type MapViewport = () => T.MapViewportOutput;

export const mapViewport: MapViewport = () => mapViewportMock;
