// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  map.config@1.0.0
// spec-hash: sha256:1e9307a37a257a642479feb77c66f42e762df381247040bc31255214cf5af39f
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:2108ce5b4aaaedf3be84bb30d619060c41f93cfb30391e7edadb1d843b642deb
// ─────────────────────────────────────────────────────────────────────────
import { sparkFetch, isMocked } from '../runtime.js';
import type * as T from '../types.js';
import { mapConfigMock } from '../mocks/map-config.js';

/**
 * Tile provider and default viewport, served once at startup.
 *
 * GET /api/map/config
 *
 */
export async function mapConfig(): Promise<T.MapConfigOutput> {
  if (isMocked("map.config")) return structuredClone(mapConfigMock);
  return sparkFetch<T.MapConfigOutput>(
    "map.config",
    "GET",
    `/api/map/config`,
    undefined,
    undefined,
  );
}
