// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  markers.stream@1.0.0
// spec-hash: sha256:9f7c6d8099a6e19e48448dd10672c0b631d0ae81c57ce2eb4ffbec602b5763f6
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:b19852d53f0d8e3c86503ceab49af037a3c053118a32f1013d7a1032621b6ee5
// ─────────────────────────────────────────────────────────────────────────
import { sparkSubscribe } from '../runtime.js';
import type * as T from '../types.js';
import { markersStreamMock } from '../mocks/markers-stream.js';

/**
 * Movement events pushed to every client watching that area.
 *
 * Returns an unsubscribe function. While `sparkConfig.mock` covers this
 * contract, the example event replays once a second so a live view can be
 * built before the server pushes anything.
 */
export function markersStream(handler: (event: T.MarkersStreamOutput) => void): () => void {
  return sparkSubscribe<T.MarkersStreamOutput>(
    "markers.stream",
    "marker.moved",
    handler,
    markersStreamMock,
  );
}
