// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  markers.list@1.0.0
// spec-hash: sha256:cee8e41453f94899f75fd9127f87c5dce6cc95a4181d446b7ee717f365c37434
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:41ae86a1c7397f5751ae125e6a8256d3826441ca90c08a093fb2e633fd5cb9a1
// ─────────────────────────────────────────────────────────────────────────
import { sparkFetch, isMocked } from '../runtime.js';
import type * as T from '../types.js';
import { markersListMock } from '../mocks/markers-list.js';

/**
 * Markers currently inside the visible bounding box.
 *
 * GET /api/markers
 * Throws SparkError BBOX_INVALID when bbox is not [w,s,e,n].
 */
export async function markersList(args: T.MarkersListInput): Promise<T.MarkersListOutput> {
  if (isMocked("markers.list")) return structuredClone(markersListMock);
  return sparkFetch<T.MarkersListOutput>(
    "markers.list",
    "GET",
    `/api/markers`,
    undefined,
    { bbox: args.bbox, since: args.since },
  );
}
