// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  markers.detail@1.0.0
// spec-hash: sha256:1c1d5d62cf22b3a650e946eda57d4c7ac000e08a101035b5d2f9e48cadac8a6e
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:4a9623acf5055e951851d18f8059ecf3aa4375e6c169dc62925898a394b18d00
// ─────────────────────────────────────────────────────────────────────────
import { sparkFetch, isMocked } from '../runtime.js';
import type * as T from '../types.js';
import { markersDetailMock } from '../mocks/markers-detail.js';

/**
 * Full detail for one marker, loaded on tap.
 *
 * GET /api/markers/:id
 * Throws SparkError MARKER_NOT_FOUND when no marker with that id.
 */
export async function markersDetail(args: T.MarkersDetailInput): Promise<T.MarkersDetailOutput> {
  if (isMocked("markers.detail")) return structuredClone(markersDetailMock);
  return sparkFetch<T.MarkersDetailOutput>(
    "markers.detail",
    "GET",
    `/api/markers/${encodeURIComponent(String(args.id))}`,
    undefined,
    undefined,
  );
}
