// ─────────────────────────────────────────────────────────────────────────
// Generated by SparkX. Do not edit this file.
// contract:  positions.ingest@1.0.0
// spec-hash: sha256:99c3eef72ebb94502d1455a5a35409549921a9365df71c3bbbc3fd7659ca256e
// Change the contract in SparkX and regenerate. Handwritten edits here are
// reported as GENERATED_EDITED and will be overwritten.
// spark-body: sha256:a9f1d08ddaf861da6e36205986043b9d02a5ebb6e160002f2ccf74c964ccfa38
// ─────────────────────────────────────────────────────────────────────────
import { sparkFetch, isMocked } from '../runtime.js';
import type * as T from '../types.js';
import { positionsIngestMock } from '../mocks/positions-ingest.js';

/**
 * A device or vehicle reporting where it is.
 *
 * POST /api/positions
 * Throws SparkError COORDS_INVALID when lat/lng out of range.
 */
export async function positionsIngest(args: T.PositionsIngestInput): Promise<T.PositionsIngestOutput> {
  if (isMocked("positions.ingest")) return structuredClone(positionsIngestMock);
  return sparkFetch<T.PositionsIngestOutput>(
    "positions.ingest",
    "POST",
    `/api/positions`,
    { deviceId: args.deviceId, lat: args.lat, lng: args.lng, headingDeg: args.headingDeg, at: args.at },
    undefined,
  );
}
